[Contract]Add WooStakingVault
woonetwork/woofi_swap_smart_contracts pull request #45
Opened 2021-11-11 09:07 UTC by merlincdj

- [ ] withdraw function

2021-11-11 09:11 UTC, merlincdj commented
Using hardhat deploy and verify on bsc testnet
https://testnet.bscscan.com/address/0xAaf8F6F1F64B29fAdF5320268A45074E2154dec7#code

2021-11-11 09:25 UTC, skyinthesea-woo requested changes
A bunch of comments to fix.

2021-11-11 09:25 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +            string(abi.encodePacked("x", ERC20(_token).name())),
"x" --->  "Interest bearing"

2021-11-11 09:25 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +        token.safeTransferFrom(msg.sender, address(this), _amount);
Please utilize our new TransferHelper method:

There's sample code in WooRouter.sol

2021-11-11 09:25 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +        token.safeTransferFrom(msg.sender, address(this), _amount);
Please utilize our new TransferHelper method:

There's sample code in WooRouter.sol

2021-11-11 09:25 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +        uint256 _pool = balance();
poolBalance

2021-11-11 09:25 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +        uint256 _before = token.balanceOf(address(this));
balanceBefore

2021-11-11 09:25 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +contract wVault is ERC20, Ownable {
WooStakingVault

Contract name's first character needs to be "UpperCase"

2021-11-11 09:25 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +    IERC20 public token;
stakedToken

2021-11-11 09:25 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +    address public controller;
Not needed anymore

2021-11-11 09:25 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +        }
uint256 totalSupply = totalSupply();
uint256 shares = totalSupply == 0 ? _amount : _amount.mul(totalSupply).div(poolBalance)

2021-11-11 09:25 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +        uint256 r = (balance().mul(_shares)).div(totalSupply());
r -> shareBalance

或者换一个你觉得有意义的名字； 别用  r

2021-11-12 02:22 UTC, skyinthesea-woo reviewed
Looks good.   

再加上unit tests就完美了

2021-11-13 16:28 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +        stakedToken = IERC20(_stakedToken);
address 的参数 require != address(0) 

可以看 WooRouter 的代码。

2021-11-13 16:28 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +        uint256 xTotalSupply = totalSupply();
nice naming for this local variable.

2021-11-13 16:28 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +        ).div(beforeShares.add(_shares));
能不能这里写一下comment ； 这个公式是什么？

这样方便后面进行维护。

2021-11-13 16:29 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +    mapping(address => UserInfo) public userInfo;
Pay attention to the code format.

2021-11-13 16:31 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +    uint256 public withdrawFee = 10; // 0.1%
稍微注释下单位

2021-11-13 16:42 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +    function reserveWithdraw(uint256 _shares) external whenNotPaused {
我建议别用 _shares 吧

就用  xWooAmount  ； _shares 都是之前 YFI 的遗留产物，而且很疑惑人。

2021-11-13 16:46 UTC, skyinthesea-woo commented on contracts/WooStakingVault.sol
> +        uint256 balanceAfter = stakedToken.balanceOf(address(this)).sub(totalReserveAmount);
call "balance()" please.

2021-11-13 16:53 UTC, skyinthesea-woo commented on test/WooStakingVault.test.ts
> +    ;[owner, user, treasury, newTreasury] = await ethers.getSigners()
这里的 ; 是什么 ？

2021-11-13 16:55 UTC, skyinthesea-woo commented
这边跑了之后 coverage 是 100% 吗？  （Vault这个class）

2021-11-13 16:55 UTC, skyinthesea-woo commented
Have a few inline comments. Others look good. 

We can do a smart contract security check on Monday.

2021-11-14 01:56 UTC, merlincdj commented on contracts/WooStakingVault.sol
> +    mapping(address => UserInfo) public userInfo;
resolved by lint-action

2021-11-14 01:56 UTC, merlincdj commented on test/WooStakingVault.test.ts
> +    ;[owner, user, treasury, newTreasury] = await ethers.getSigners()
lint-action make this. # 9e65944b2ad339d73060fa61e335631978a14b98

2021-11-15 02:24 UTC, merlincdj commented on contracts/WooStakingVault.sol
> +    function reserveWithdraw(uint256 _shares) external whenNotPaused {
shares涉及到share price(单位净值)和cost share price(用户成本单位净值)，我建议不改动

2021-11-15 06:52 UTC, skyinthesea-woo approved these changes

2021-11-15 11:27 UTC, merlincdj commented
> 这边跑了之后 coverage 是 100% 吗？ （Vault这个class）

only line 115 not coverage, maybe it's impossible situation, keep this logic for safety.

2021-11-15 11:28 UTC, merged